# Generated by Django 3.2.9 on 2021-12-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='listings',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
